from cgitb import text
from faulthandler import disable
from genericpath import exists
from tkinter import *
import math
from tkinter import ttk
from tkinter import font


#Definicion de funciones
def Seleccionar():
    pass

def crearTabla():
    if opcion.get() == 2:
        frame1 = Frame(root)
        frame1.pack(side=BOTTOM)
        frame1.config(width=380, height=220)
        label = Label(frame1, text ="A1")
        label.grid(row=1, column=0, padx=5, pady=5)
        label2 = Label(frame1, text ="A2")
        label2.grid(row=2, column=0, padx=5, pady=5)
        label3 = Label(frame1, text ="B1")
        label3.grid(row=0, column=1, padx=5, pady=5)
        entry1_R2 = Entry(frame1)
        entry1_R2.grid(row=1, column=1, padx=5, pady=5)
        entry1_R2.config(justify=CENTER)
        entry2_R2 = Entry(frame1)
        entry2_R2.grid(row=2, column=1, padx=5, pady=5)
        entry2_R2.config(justify=CENTER)
        label3 = Label(frame1, text ="B2")
        label3.grid(row=0, column=2, padx=5, pady=5)
        entry3_R2 = Entry(frame1)
        entry3_R2.grid(row=1, column=2, padx=5, pady=5)
        entry3_R2.config(justify=CENTER)
        entry4_R2 = Entry(frame1)
        entry4_R2.grid(row=2, column=2, padx=5, pady=5)
        entry4_R2.config(justify=CENTER)
        button1 = Button(frame1, text="Calcular").pack()

    elif opcion.get() == 3:
        frame2 = Frame(root)
        frame2.pack(side=BOTTOM)
        frame2.config(width=380, height=220)
        label = Label(frame2, text ="A1")
        label.grid(row=1, column=0, padx=5, pady=5)
        label2 = Label(frame2, text ="A2")
        label2.grid(row=2, column=0, padx=5, pady=5)
        label3 = Label(frame2, text ="A3")
        label3.grid(row=3, column=0, padx=5, pady=5)
        label4 = Label(frame2, text ="B1")
        label4.grid(row=0, column=1, padx=5, pady=5)
        entry1_R3 = Entry(frame2)
        entry1_R3.grid(row=1, column=1, padx=5, pady=5)
        entry1_R3.config(justify=CENTER)
        entry2_R3 = Entry(frame2)
        entry2_R3.grid(row=2, column=1, padx=5, pady=5)
        entry2_R3.config(justify=CENTER)
        entry3_R3 = Entry(frame2)
        entry3_R3.grid(row=3, column=1, padx=5, pady=5)
        entry3_R3.config(justify=CENTER)
        label5 = Label(frame2, text ="B2")
        label5.grid(row=0, column=2, padx=5, pady=5)
        entry4_R3 = Entry(frame2)
        entry4_R3.grid(row=1, column=2, padx=5, pady=5)
        entry4_R3.config(justify=CENTER)
        entry5_R3 = Entry(frame2)
        entry5_R3.grid(row=2, column=2, padx=5, pady=5)
        entry5_R3.config(justify=CENTER)
        entry6_R3 = Entry(frame2)
        entry6_R3.grid(row=3, column=2, padx=5, pady=5)
        entry6_R3.config(justify=CENTER)
        label6 = Label(frame2, text ="B3")
        label6.grid(row=0, column=3, padx=5, pady=5)
        entry7_R3 = Entry(frame2)
        entry7_R3.grid(row=1, column=3, padx=5, pady=5)
        entry7_R3.config(justify=CENTER)
        entry8_R3 = Entry(frame2)
        entry8_R3.grid(row=2, column=3, padx=5, pady=5)
        entry8_R3.config(justify=CENTER)
        entry9_R3 = Entry(frame2)
        entry9_R3.grid(row=3, column=3, padx=5, pady=5)
        entry9_R3.config(justify=CENTER)
        button2 = Button(frame2, text="Calcular").pack()

    elif opcion.get() == 4:
        frame3 = Frame(root)
        frame3.pack(side=BOTTOM)
        frame3.config(width=380, height=220)
        label = Label(frame3, text ="A1")
        label.grid(row=1, column=0, padx=5, pady=5)
        label2 = Label(frame3, text ="A2")
        label2.grid(row=2, column=0, padx=5, pady=5)
        label3 = Label(frame3, text ="A3")
        label3.grid(row=3, column=0, padx=5, pady=5)
        label4 = Label(frame3, text ="A4")
        label4.grid(row=4, column=0, padx=5, pady=5)
        label5 = Label(frame3, text ="B1")
        label5.grid(row=0, column=1, padx=5, pady=5)
        entry1_R3 = Entry(frame3)
        entry1_R3.grid(row=1, column=1, padx=5, pady=5)
        entry1_R3.config(justify=CENTER)
        entry2_R3 = Entry(frame3)
        entry2_R3.grid(row=2, column=1, padx=5, pady=5)
        entry2_R3.config(justify=CENTER)
        entry3_R3 = Entry(frame3)
        entry3_R3.grid(row=3, column=1, padx=5, pady=5)
        entry3_R3.config(justify=CENTER)
        entry4_R3 = Entry(frame3)
        entry4_R3.grid(row=4, column=1, padx=5, pady=5)
        entry4_R3.config(justify=CENTER)
        label6 = Label(frame3, text ="B2")
        label6.grid(row=0, column=2, padx=5, pady=5)
        entry5_R3 = Entry(frame3)
        entry5_R3.grid(row=1, column=2, padx=5, pady=5)
        entry5_R3.config(justify=CENTER)
        entry6_R3 = Entry(frame3)
        entry6_R3.grid(row=2, column=2, padx=5, pady=5)
        entry6_R3.config(justify=CENTER)
        entry7_R3 = Entry(frame3)
        entry7_R3.grid(row=3, column=2, padx=5, pady=5)
        entry7_R3.config(justify=CENTER)
        entry8_R3 = Entry(frame3)
        entry8_R3.grid(row=4, column=2, padx=5, pady=5)
        entry8_R3.config(justify=CENTER)
        label7 = Label(frame3, text ="B3")
        label7.grid(row=0, column=3, padx=5, pady=5)
        entry9_R3 = Entry(frame3)
        entry9_R3.grid(row=1, column=3, padx=5, pady=5)
        entry9_R3.config(justify=CENTER)
        entry10_R3 = Entry(frame3)
        entry10_R3.grid(row=2, column=3, padx=5, pady=5)
        entry10_R3.config(justify=CENTER)
        entry11_R3 = Entry(frame3)
        entry11_R3.grid(row=3, column=3, padx=5, pady=5)
        entry11_R3.config(justify=CENTER)
        entry12_R3 = Entry(frame3)
        entry12_R3.grid(row=4, column=3, padx=5, pady=5)
        entry12_R3.config(justify=CENTER)
        label8 = Label(frame3, text ="B4")
        label8.grid(row=0, column=4, padx=5, pady=5)
        entry13_R3 = Entry(frame3)
        entry13_R3.grid(row=1, column=4, padx=5, pady=5)
        entry13_R3.config(justify=CENTER)
        entry14_R3 = Entry(frame3)
        entry14_R3.grid(row=2, column=4, padx=5, pady=5)
        entry14_R3.config(justify=CENTER)
        entry15_R3 = Entry(frame3)
        entry15_R3.grid(row=3, column=4, padx=5, pady=5)
        entry15_R3.config(justify=CENTER)
        entry16_R3 = Entry(frame3)
        entry16_R3.grid(row=4, column=4, padx=5, pady=5)
        entry16_R3.config(justify=CENTER)
        button3 = Button(frame3, text="Calcular").pack()
    opcion.set(None)

#Configuración de la Interfaz
root=Tk()
menubar = Menu(root)
root.config(menu=menubar)
root.title("Ejercicio 3")
root.resizable(False,False)
root.geometry('720x540')
root.config(bg = "lightblue")

filemenu = Menu(menubar, tearoff=0)
editmenu = Menu(menubar, tearoff=0)
helpmenu = Menu(menubar, tearoff=0)

menubar.add_cascade(label = "Archivo", menu = filemenu)
menubar.add_cascade(label = "Editar", menu = editmenu)
menubar.add_cascade(label = "Ayuda", menu = helpmenu)

#Primer Marco de la interfaz
frame = Frame(root)
frame.pack(side=TOP)
frame.config(width=380, height=220)
texto= Label(frame, text=" Seleccionar el valor de R ").pack()
#texto.config(font="Consolas")
opcion = IntVar()
Radiobutton(frame, text=" R = 2 ", variable=opcion, value=2,).pack()
Radiobutton(frame, text=" R = 3 ", variable=opcion, value=3).pack()
Radiobutton(frame, text=" R = 4 ", variable=opcion, value=4).pack()
button = Button(frame, text="Aceptar", command=crearTabla).pack()
#Finalmente bucle
root.mainloop()